FROM node:24.21.0-bookworm-slim@sha256:0e0ff40c39bc087845bfb27465a0df4ea419520094bc35842ff83dd8cbe6f9b6
RUN apt-get update && apt-get install -y --no-install-recommends openssl=3.0.22-1~deb12u1 && rm -rf /var/lib/apt/lists/*
RUN npm install --global npm@11.18.0
WORKDIR /workspace/apps/api
RUN mkdir -p node_modules && chown -R node:node /workspace
USER node
